if not config:
    configfile: "config/config.yaml"


def _get_all_targets(wildcards):
    # Default targets are the metadata TSV and sequences FASTA files
    all_targets = [
        "data/sequences.fasta",
        "data/metadata.tsv"
    ]

    return all_targets

rule all:
    input: _get_all_targets


include: "workflow/snakemake_rules/fetch_from_ncbi.smk"
include: "workflow/snakemake_rules/curate.smk"
include: "workflow/snakemake_rules/sort.smk"
